apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: customer-notification-llm
spec:
  type: conversation.openai
  version: v1
  metadata:
    - name: key
      value: your open api key
    - name: model
      value: gpt-4-turbo
    - name: cacheTTL
      value: 10m      